version: '3.3'
services:
  db:
      image: postgres:9.5
      container_name: postgres
      environment:
        - POSTGRES_DB=ms1-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5432:5432
